# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDB_IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDB_IOS
  pod 'ObjectMapper', '~> 3.3'
  pod 'SwiftLint'

end
