# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Cosmos', '~> 16.0'

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
target 'MovieDB_IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDB_IOS
  pod 'ObjectMapper', '~> 3.3'
  pod 'SwiftLint'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Cosmos', '~> 16.0'
  pod 'DropDown'
  pod 'SQLite.swift', '~> 0.11.5'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod "youtube-ios-player-helper", "~> 0.1.4"
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Google'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
end
